### ISSUE TITLE
testImportKeyring error

### ISSUE THREAD

**Issue by diracdeltas** [yahoo/end-to-end#20]
Repro steps:
1. ./do.sh testserver
2. go to  http://localhost:8000/src/javascript/crypto/e2e/extension/ui/panels/keyringmgmt/keyringmgmtmini_test.html?runTests=testImportKeyring in Chrome (I run Version 41.0.2272.89 (64-bit)).

I get the following error:

```
localhost:8000/src/javascript/crypto/e2e/extension/ui/panels/keyringmgmt/keyringmgmtmini_test.html?runTests=testImportKeyring
1 of 12 tests run in 521ms.
0 passed, 1 failed, 11 suppressed by querystring.
521 ms/test. 297 files loaded.
.
09:35:35.702  Start
09:35:35.717  testImportKeyring [testImportKeyring] : FAILED (run individually)
09:35:35.720  ERROR in testImportKeyring [testImportKeyring]
Cannot read property 'closure_lm_420544' of null
> (unknown)
> Object.goog.events.getListenerMap_ at http://localhost:8000/javascript/closure/events/events.js:932:24
> Object.goog.events.listen_ at http://localhost:8000/javascript/closure/events/events.js:229:33
> Object.goog.events.listen at http://localhost:8000/javascript/closure/events/events.js:183:24
> goog.events.EventHandler.listen_ at http://localhost:8000/javascript/closure/events/eventhandler.js:175:35
> goog.events.EventHandler.listen at http://localhost:8000/javascript/closure/events/eventhandler.js:121:15
> panels.KeyringMgmtMini.enterDocument at http://localhost:8000/javascript/crypto/e2e/extension/ui/panels/keyringmgmt/keyringmgmtmini.js:271:7
> goog.ui.Component.render_ at http://localhost:8000/javascript/closure/ui/component.js:713:10
> goog.ui.Component.render at http://localhost:8000/javascript/closure/ui/component.js:655:8
> testImportKeyring at http://localhost:8000/javascript/crypto/e2e/extension/ui/panels/keyringmgmt/keyringmgmtmini_test.js:150:9
> goog.testing.TestCase.Test.execute at http://localhost:8000/javascript/closure/testing/testcase.js:1293:12
> goog.testing.AsyncTestCase.doExecute_ at http://localhost:8000/javascript/closure/testing/asynctestcase.js:878:19
> goog.testing.AsyncTestCase.callTopOfStackFunc_ at http://localhost:8000/javascript/closure/testing/asynctestcase.js:756:10
> goog.testing.AsyncTestCase.pump_ at http://localhost:8000/javascript/closure/testing/asynctestcase.js:805:16
> goog.testing.AsyncTestCase.runTests at http://localhost:8000/javascript/closure/testing/asynctestcase.js:508:8
> goog.testing.TestRunner.execute at http://localhost:8000/javascript/closure/testing/testrunner.js:270:19
09:35:36.223  Done
```

**Comment by diracdeltas** [comment]
This doesn't happen in a build with older versions of closure library and closure compiler.

Test passes:

```
mr log: end-to-end/lib/closure-compiler
34adc40bd10339b7c8a2ae2b2cb487323db21e68 Fix a compiler crash with ES5 inputs when the language_out is ES6. The ES6->ES5 passes were being enabled incorrectly based on the assumption that was the only kind of transpilation. ------------- Created by MOE: http://code.google.com/p/moe-java MOE_MIGRATED_REVID=85117586

mr log: end-to-end/lib/closure-library
2a79f2bc6b43115631fc6a1000e027c9d863a24d Revert e9dcd0ba641a8a3817e49b295a347954e47b3379.

mr log: end-to-end/lib/closure-stylesheets
3eb80f827270e73abd882ba69dbc3f3182a55889 Comment to be consistent with implementation that unquoted url() doesn't accept <ESCAPE>.      Change on 2014/02/25 by iwami <iwami@google.com> ------------- Created by MOE: http://code.google.com/p/moe-java MOE_MIGRATED_REVID=62182489

mr log: end-to-end/lib/zlib.js
b99bd33d485d63e93310b911a1f8dbf9ceb265d5 Merge branch 'release/0.2.0'
```

test fails:

```
mr log: end-to-end/lib/closure-compiler
1e27e0f80b5d42f85763a4e17e6f93746120dfbb A few more getTypeRegistry changes in javatests. This is the last CL about getTypeRegistry cleanups. ------------- Created by MOE: http://code.google.com/p/moe-java MOE_MIGRATED_REVID=88586005

mr log: end-to-end/lib/closure-library
848686a4791374beaa99478cdf37d95deb2752e1 This merge has been reverted since it breaks tests on IE8. The presence of 'val' should be enforced by the compiler since it is not optional.

mr log: end-to-end/lib/closure-stylesheets
3eb80f827270e73abd882ba69dbc3f3182a55889 Comment to be consistent with implementation that unquoted url() doesn't accept <ESCAPE>.      Change on 2014/02/25 by iwami <iwami@google.com> ------------- Created by MOE: http://code.google.com/p/moe-java MOE_MIGRATED_REVID=62182489

mr log: end-to-end/lib/zlib.js
b99bd33d485d63e93310b911a1f8dbf9ceb265d5 Merge branch 'release/0.2.0'
```
